name: Deploy Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: FTP Deploy (Production)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /prod/
          protocol: ftp
          exclude: |
            **/.git*
            **/.github*
            **/README.md
